version: '3.8'

services:
  kudos-krab:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
      - DATABASE_URL=${DATABASE_URL}
      - MONTHLY_QUOTA=${MONTHLY_QUOTA:-10}
      - SLACK_BOT_USER_ID=${SLACK_BOT_USER_ID}
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 